### ISSUE TITLE
unable to install indra_world, error: Multiple top-level packages discovered in a flat-layout

### ISSUE THREAD

**Issue by MagJ1** [indralab/indra_world#66]
Hello Everyone, 

unfortunately, I am not able to install indra_world as explained via `$ pip install git+https://github.com/indralab/indra_world.git`

I get the error message: 

      warnings.warn(msg, warning_class)
      error: Multiple top-level packages discovered in a flat-layout: ['docker', 'indra_world'].
      
      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.
      
      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:
      
      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names
      
      To find more information, look for "package discovery" on setuptools docs.
      [end of output]
  
      note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      × Encountered error while generating package metadata.
     ╰─> See above for output.

       note: This is an issue with the package mentioned above, not pip.
       hint: See above for details.

I trie to run it on vscode and I have MacOS 13.1 currently installed. 

Any help appreciated! Thank you!

**Comment by bgyori** [comment]
Thanks for the report @MagJ1. This occurs on the most recent versions of setuptools. I fixed it using the 3-rd option shown in the error message.
